-- Legacy staff bootstrap retired. The Árajánlat uses its own two Auth
-- accounts. Apply quote_auth_isolation.sql, quote_auth_provision.sql and
-- quote_auth_cutover.sql in that order during the controlled cutover.
