import './modules/app-install.js';
import { mountCustomerSearch } from './modules/customer-search.js';
import { startAppointmentNotifications, stopAppointmentNotifications } from './modules/appointment-notifications.js';
import { mountAppointments } from './modules/appointments.js';
import { db, configured, rows, rpc } from './services/supabase-service.js';
import { STAFF_ACCOUNTS, SUPABASE_URL, SUPABASE_KEY } from './config.js';
import { offerEmail, composeEmail } from './services/email-service.js';
import { calculateItem, calculateTotal, money, dateTime } from './modules/quote-calculator.js';

const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={customers:[],projects:[],quotes:[],catalog:[],templates:[],customer:null,project:null,quote:null,version:null,items:[],timer:null,companyId:null,session:null,selectedAccount:null};
function status(message,error=false){$('#status').textContent=message;$('#status').classList.toggle('error',error)}
function fail(error){console.error(error);status(error?.message||'Váratlan hiba történt. Próbálja újra.',true)}
async function save(table,record){const {data,error}=await db.from(table).upsert(record).select().single();if(error)throw error;return data}
async function remove(table,id){const {error}=await db.from(table).delete().eq('id',id);if(error)throw error}
function formDialog(title,fields,onSubmit){$('#dialog-title').textContent=title;$('#dialog-fields').innerHTML=fields;const dlg=$('#form-dialog');dlg.showModal();$('#dialog-form').onsubmit=async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));const button=event.target.querySelector('.dialog-actions .primary');button.disabled=true;try{const message=await onSubmit(data);dlg.close();status(message||'Mentve.')}catch(error){fail(error)}finally{button.disabled=false}}}
$('#dialog-close').onclick=$('#dialog-cancel').onclick=()=>$('#form-dialog').close();
function field(name,label,value='',type='text',required=false){return `<label>${label}<input name="${name}" type="${type}" ${type==='number'?'step="any" min="0"':''} value="${esc(value)}" ${required?'required':''}></label>`}
function area(name,label,value=''){return `<label>${label}<textarea name="${name}">${esc(value)}</textarea></label>`}
async function init(){if(!configured){$('#setup').hidden=false;return}selectAccount(localStorage.getItem('quote_last_account'));const {data:{session}}=await db.auth.getSession();await authState(session);db.auth.onAuthStateChange((_event,nextSession)=>{setTimeout(()=>authState(nextSession).catch(fail),0)})}
async function authState(session){startAppointmentNotifications(null);state.session=session;const account=Object.entries(STAFF_ACCOUNTS).find(([,value])=>value.email.toLowerCase()===session?.user?.email?.toLowerCase());$('#login').hidden=Boolean(account);$('#workspace').hidden=true;$('#nav').hidden=true;if(!account){if(session)status('Ehhez a fiókhoz nincs árajánlatkészítői hozzáférés.',true);return}selectAccount(account[0]);localStorage.setItem('quote_last_account',account[0]);
 try{const staff=await rows('quote_staff',q=>q.select('user_id,company_id').eq('user_id',session.user.id).limit(1));if(!staff[0]?.company_id){$('#login').hidden=false;status('Ehhez a fiókhoz nincs árajánlatkészítői hozzáférés.',true);return}state.companyId=staff[0].company_id;startAppointmentNotifications(session.user.id);$('#workspace').hidden=false;$('#nav').hidden=false;status('');await refresh();const message=await syncCustomers();await refresh();if(message)status(message)}catch(error){$('#login').hidden=false;fail(error)}}
function selectAccount(key){if(!STAFF_ACCOUNTS[key])return;state.selectedAccount=key;document.querySelectorAll('[data-account]').forEach(button=>{const active=button.dataset.account===key;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))})}
document.querySelectorAll('[data-account]').forEach(button=>button.onclick=()=>{selectAccount(button.dataset.account);localStorage.setItem('quote_last_account',button.dataset.account);$('#login-help').textContent=`${STAFF_ACCOUNTS[button.dataset.account].name} kiválasztva. A sikeres belépést ez az eszköz megjegyzi.`});
$('#login-form').onsubmit=async event=>{event.preventDefault();const pin=new FormData(event.target).get('pin');if(!state.selectedAccount){status('Válaszd ki a neved.',true);return}const button=event.target.querySelector('button.primary');button.disabled=true;try{const {error}=await db.auth.signInWithPassword({email:STAFF_ACCOUNTS[state.selectedAccount].email,password:pin});if(error){status('Hibás PIN-kód vagy sikertelen belépés. Próbáld újra.',true);return}localStorage.setItem('quote_last_account',state.selectedAccount);event.target.reset()}catch(error){fail(error)}finally{button.disabled=false}};
$('#signout').onclick=async()=>{let notificationFailed=false;try{await stopAppointmentNotifications()}catch{notificationFailed=true}try{const {error}=await db.auth.signOut();if(error)throw error;state.companyId=null;await authState(null);if(notificationFailed)status('Kijelentkeztél. A riasztás kikapcsolását ellenőrizd a böngésző értesítési beállításaiban.',true)}catch(error){fail(error)}};
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>showView(button.dataset.view));
function showView(view){$('#customers-view').hidden=view!=='customers';$('#quotes-view').hidden=view!=='quotes';$('#projects-view').hidden=view!=='projects';document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view))}
async function refresh(){
 const merged=await rpc('quote_customers_merge_duplicates',{});
 state.customerAliases??={};for(const pair of merged){state.customerAliases[pair.from]=pair.to;if(state.customer?.id===pair.from)state.customer.id=pair.to;}

 [state.customers,state.projects,state.quotes,state.catalog,state.templates,state.syncQueue]=await Promise.all([
 rpc('quote_clients_list',{}),
 rows('quote_projects',q=>q.select('*').order('created_at',{ascending:false})),
 rows('quote_quotes',q=>q.select('*').order('created_at',{ascending:false})),
 rows('quote_price_catalog',q=>q.select('*').eq('active',true).order('source_row')),
 rows('quote_templates',q=>q.select('*').order('name')),
 rows('quote_customer_sync',q=>q.select('client_id,last_error').is('synced_at',null))]);
 renderCustomers();renderProjects();renderQuotes();
}
let syncRunning=false,dataRefreshRunning=false;
async function syncCustomers(){
 if(syncRunning||!state.session)return '';
 syncRunning=true;
 try{
  const {data:{session},error:sessionError}=await db.auth.getSession();
  if(sessionError||!session)return 'A közös ügyféllista frissítéséhez jelentkezz be újra.';
  const response=await fetch(SUPABASE_URL+'/functions/v1/quote-customer-sync',{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:'{}',signal:AbortSignal.timeout(100000)});
  if(!response.ok){console.warn('quote_customer_sync_unavailable: HTTP '+response.status);return response.status===401?'A közös ügyféllista frissítéséhez jelentkezz be újra.':'A közös ügyféllista most nem frissíthető. Az itt mentett adatok megmaradnak.';}
  const data=await response.json();
  if(data.busy)return 'Az ügyféllista frissítése már folyamatban van.';
  if(data.failed||data.pending)return 'A közös ügyféllista frissült. Néhány ügyfélnél még ellenőrizni kell az adatokat.';
  return data.imported||data.synced?'A közös ügyféllista frissült.':'';
 }catch(error){console.warn('quote_customer_sync_unavailable: '+error?.name);return 'A közös ügyféllista most nem frissíthető. Az itt mentett adatok megmaradnak.'}finally{syncRunning=false}
}
async function refreshCommonCustomers(silent=false){
 if(!state.session||syncRunning||dataRefreshRunning||$('#form-dialog').open)return;
 const button=$('#sync-customers');button.disabled=true;
 try{
  if(!silent)status('Ügyféllista frissítése…');
  const message=await syncCustomers();await refresh();
  if(!$('#customers-view').hidden&&state.customer){const projectId=state.project?.id;const current=state.customers.find(c=>c.id===state.customer.id);if(current){await openCustomer(current.id);if(projectId&&state.projects.some(p=>p.id===projectId&&p.client_id===current.id))await openProject(projectId)}}
  if(message||!silent)status(message||'Az ügyféllista naprakész.');
 }catch(e){if(!silent)fail(e)}finally{button.disabled=false}
}
$('#sync-customers').onclick=()=>refreshCommonCustomers();
$('#refresh-data').onclick=async()=>{
 if($('#form-dialog').open){status('Előbb mentsd vagy zárd be a megnyitott űrlapot.');return}
 if(syncRunning){status('Az ügyféllista frissítése már folyamatban van.');return}
 const button=$('#refresh-data');button.disabled=true;dataRefreshRunning=true;$('#workspace').inert=true;$('#nav').inert=true;
 try{
  await flushQuoteSave();status('Adatok frissítése…');
  const message=await syncCustomers();
  const customerId=state.customer?.id,projectId=state.project?.id,quoteId=state.quote?.id;
  const quoteVisible=!$('#quotes-view').hidden;
  await refresh();
  if(!$('#customers-view').hidden&&customerId&&state.customers.some(c=>c.id===customerId)){
   await openCustomer(customerId);
   if(projectId&&state.projects.some(p=>p.id===projectId&&p.client_id===customerId))await openProject(projectId);
  }
  if(quoteVisible&&quoteId&&state.quotes.some(q=>q.id===quoteId))await openQuote(quoteId);
  status(message||'Az adatok naprakészek.');
  if('serviceWorker'in navigator){const reg=await navigator.serviceWorker.getRegistration();await reg?.update();if(reg?.waiting)$('#update-banner').hidden=false}
 }catch(error){fail(error)}finally{button.disabled=false;dataRefreshRunning=false;$('#workspace').inert=false;$('#nav').inert=false}
};
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshCommonCustomers(true)});
window.addEventListener('online',()=>refreshCommonCustomers(true));
setInterval(()=>{if(!document.hidden)refreshCommonCustomers(true)},120000);
function customerAddresses(c){return [...new Set(String(c?.project_address||'').split('\n').map(x=>x.trim()).filter(Boolean))]}
function projectTitle(p){return [p?.project_code,p?.name].filter(Boolean).join(' – ')}
const customerSearch=mountCustomerSearch({input:$('#customer-search'),results:$('#customer-results'),count:$('#customers-list'),customers:()=>state.customers.filter(c=>c.source_customer_id||c.shared_sync_enabled),onSelect:async id=>{await openCustomer(id);$('#customer-detail').scrollIntoView({behavior:'smooth',block:'start'})},fail});
function renderCustomers(){customerSearch.render()}
$('#new-customer').onclick=()=>editCustomer();
function editCustomer(c={}){
 const rawType=c.client_type==='person'?'Magánszemély':c.client_type==='company'?'Cég':c.client_type||'';
 const types=['','Magánszemély','Cég'];
 if(rawType&&!types.includes(rawType))types.push(rawType);
 const options=types.map(t=>'<option value="'+esc(t)+'" '+(t===rawType?'selected':'')+'>'+esc(t||'Nincs megadva')+'</option>').join('');
 const sharing='<p class="muted">Az ügyfél automatikusan bekerül a közös Munkalap és Kassza ügyféllistába.</p>';
 const fields='<label>Típus<select name="client_type">'+options+'</select></label><div class="grid">'+field('name','Név / cégnév',c.name,'text',true)+field('contact_name','Kapcsolattartó',c.contact_name)+field('phone','Telefon',c.phone,'tel')+field('email','Email',c.email,'email')+field('billing_address','Számlázási cím – Árajánlat',c.billing_address)+'</div>'+area('project_address','Munkavégzés címei (címenként külön sor)',c.project_address)+area('notes','Közös ügyfélmegjegyzés',c.notes)+sharing;
 formDialog(c.id?'Ügyfél szerkesztése':'Új ügyfél',fields,async data=>{
  const saved=await rpc('quote_clients_upsert',{p_id:c.id||null,p_name:data.name,p_client_type:data.client_type,p_contact_name:data.contact_name,p_phone:data.phone,p_email:data.email,p_billing_address:data.billing_address,p_project_address:data.project_address,p_notes:data.notes,p_share:true,p_expected_revision:c.sync_revision??null});
  await refresh();const message=await syncCustomers();await refresh();await openCustomer(state.customerAliases?.[saved.id]||saved.id);return message;
 });
}
function customerSyncHtml(c,pending){
 let html=c.shared_sync_enabled&&!c.source_customer_id?'<p class="muted">Az új ügyfél megjelenése a Munkalapban és Kasszában folyamatban van.</p>':'';
 if(!c.is_active)html+='<p class="price-warning">A közös törzsben inaktív vagy jóváhagyásra vár.</p>';
 if(pending)html+='<p class="muted">Az ügyfél itt mentve van. A Munkalap és Kassza ügyféllistájának frissítése még folyamatban van.</p>';
 return html;
}
async function openCustomer(id){state.customer=state.customers.find(c=>c.id===id);const c=state.customer;if(!c)throw Error('Az ügyfél nem található. Frissítsd a listát.');$('#customer-search').value=c.name;customerSearch.close();const pending=state.syncQueue?.find(x=>x.client_id===id);$('#customer-detail').hidden=false;const projects=state.projects.filter(p=>p.client_id===id);
 $('#customer-detail').innerHTML=`<div class="detail-head"><div><p class="eyebrow">ÜGYFÉL</p><h2>${esc(c.name)}</h2><p class="muted">${esc(c.email||'')} · ${esc(c.phone||'')}</p></div><div class="toolbar"><button id="edit-customer" class="secondary">Szerkesztés</button><button id="new-project" class="primary">+ Új projekt</button></div></div><h3>Munkavégzés címei</h3>${customerAddresses(c).length?'<ul class="customer-addresses">'+customerAddresses(c).map(a=>'<li>'+esc(a)+'</li>').join('')+'</ul>':'<p class="muted">Nincs megadva cím.</p>'}${customerSyncHtml(c,pending)}<h3>Projektek</h3><div class="list">${projects.map(p=>`<button class="list-row" data-project="${p.id}"><span><strong>${esc(projectTitle(p))}</strong><small>${esc(p.status)} · ${esc(p.work_address||'')}</small></span><span>Megnyitás →</span></button>`).join('')||'<p class="muted">Még nincs projekt.</p>'}</div><div id="project-detail"></div>`;
 $('#edit-customer').onclick=()=>editCustomer(c);$('#new-project').onclick=()=>editProject();document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project));}
function editProject(p={}){const addresses=customerAddresses(state.customer);const address=p.work_address||(addresses.length===1?addresses[0]:'');formDialog(p.id?'Projekt szerkesztése':'Új projekt',`${field('name','Projekt neve',p.name,'text',true)}<label>Munkavégzés címe<input name="work_address" list="project-addresses" value="${esc(address)}"><datalist id="project-addresses">${addresses.map(a=>'<option value="'+esc(a)+'"></option>').join('')}</datalist></label><label>Státusz<select name="status">${['Új érdeklődés','Adatbekérő kiküldve','Ügyfél kitöltötte','Felmérés szükséges','Felmérve','Árajánlat készül','Árajánlat elküldve','Módosítás alatt','Elfogadva','Elutasítva','Lezárva'].map(s=>`<option ${p.status===s?'selected':''}>${s}</option>`).join('')}</select></label><label class="check-label"><input type="checkbox" name="meeting_required" ${p.meeting_required?'checked':''}> Találkozó szükséges – időpontfoglaló az adatbekérőben</label>${area('description','Rövid leírás',p.description)}${area('internal_notes','Belső megjegyzés',p.internal_notes)}${area('client_notes','Ügyfél megjegyzése',p.client_notes)}`,async data=>{const project=await save('quote_projects',{...data,meeting_required:Boolean(data.meeting_required),client_id:state.customer.id,...(p.id?{id:p.id}:{})});if(!p.id)await db.from('quote_timeline').insert({project_id:project.id,event:'Projekt létrehozva'});await refresh();await openCustomer(state.customer.id);await openProject(project.id)})}
function requestHtml(request){const a=request.answers||{};const labels={name:'Név',email:'Email',phone:'Telefon',work_address:'Helyszín',work_type:'Munka típusa',description:'Leírás',area_m2:'Terület (m²)',length_fm:'Hosszúság (fm)',width_m:'Szélesség (m)',count:'Darabszám',gate_cm:'Kapuszélesség (cm)',machine_access:'Géppel megközelíthető',water:'Víz',power:'Áram',access_note:'Megközelítés',note:'Megjegyzés'};const entries=Object.entries(labels).filter(([key])=>a[key]!==null&&a[key]!==undefined&&a[key]!=='').map(([key,label])=>`<div><dt>${label}</dt><dd>${esc(({yes:'Igen',no:'Nem'})[a[key]]||a[key])}</dd></div>`).join('');const files=Array.isArray(a.files)?a.files:[];return `<details><summary>${dateTime(request.submitted_at)} · ${esc(a.name||'Ügyfél válasza')}</summary><dl>${entries}</dl>${files.length?`<h4>Jelzett dokumentumok</h4><ul>${files.map(f=>`<li>${esc(f.name)} · ${esc(f.type||'ismeretlen típus')}</li>`).join('')}</ul>`:''}</details>`}
async function openProject(id){state.project=state.projects.find(p=>p.id===id);const p=state.project;const quotes=state.quotes.filter(q=>q.project_id===id);const [timeline,clientRequests,receivedFiles]=await Promise.all([rows('quote_timeline',q=>q.select('*').eq('project_id',id).order('occurred_at',{ascending:false})),rows('quote_client_requests',q=>q.select('*').eq('project_id',id).order('submitted_at',{ascending:false})),rows('quote_received_files',q=>q.select('*').eq('project_id',id).order('received_at',{ascending:false}))]);
 $('#project-detail').innerHTML=`<section class="panel"><div class="detail-head"><div><p class="eyebrow">${esc(p.project_code)}</p><h2>${esc(p.name)}</h2><p>${esc(p.work_address||'')}</p><p class="muted">${esc(p.status)}</p></div><div class="toolbar"><button id="edit-project" class="secondary">Szerkesztés</button><button id="new-quote" class="primary">+ Új árajánlat</button></div></div><div class="toolbar"><button id="request-link" class="secondary">Ügyfél adatbekérő link</button><button id="survey-note" class="secondary">+ Felmérési jegyzet</button><button id="file-note" class="secondary">+ Dokumentumadat</button></div><h3>Árajánlatok</h3><div class="list">${quotes.map(q=>`<button class="list-row" data-quote="${q.id}">${esc(q.number)} · ${esc(q.title||'')} →</button>`).join('')||'<p class="muted">Még nincs árajánlat.</p>'}</div><div id="project-appointments"></div><h3>Ügyfél adatbekérő</h3>${clientRequests.map(requestHtml).join('')||'<p class="muted">Még nem érkezett vissza adatbekérő.</p>'}<h3>Dokumentumok</h3><div class="timeline">${receivedFiles.map(f=>`<p><strong>${esc(f.file_name)}</strong><br><small>${dateTime(f.received_at)} · ${esc(f.file_type||'')} ${esc(f.note||'')}</small></p>`).join('')||'<p class="muted">Még nincs külön rögzített dokumentumadat.</p>'}</div><h3>Idővonal</h3><div class="timeline">${timeline.map(t=>`<p><strong>${esc(t.event)}</strong><br><small>${dateTime(t.occurred_at)} ${esc(t.note||'')}</small></p>`).join('')||'<p>Még nincs esemény.</p>'}</div></section>`;
 $('#edit-project').onclick=()=>editProject(p);$('#new-quote').onclick=()=>newQuote(p);$('#request-link').onclick=async event=>{const button=event.currentTarget;button.disabled=true;status('Adatbekérő link létrehozása…');try{await createToken(p.id,null,'request',state.customers.find(c=>c.id===p.client_id)?.email||'')}finally{button.disabled=false}};$('#survey-note').onclick=()=>formDialog('Felmérési jegyzet',`${area('note','Megjegyzés')}<label>Időpont<input type="datetime-local" name="occurred_at" required></label>`,async d=>{await save('quote_timeline',{project_id:p.id,event:'Helyszíni felmérés',note:d.note,occurred_at:new Date(d.occurred_at).toISOString()});await openProject(p.id)});$('#file-note').onclick=()=>formDialog('Dokumentumadat rögzítése',`${field('file_name','Fájlnév','', 'text',true)}${field('file_type','Típus')}${area('note','Megjegyzés')}`,async d=>{await save('quote_received_files',{project_id:p.id,...d});await openProject(p.id)});
 document.querySelectorAll('[data-quote]').forEach(b=>b.onclick=()=>openQuote(b.dataset.quote));
 await mountAppointments($('#project-appointments'),p,{formDialog,refreshProject:()=>openProject(p.id),fail,status});}
async function newQuote(p){const number=`DK-${new Date().getFullYear()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const quote=await save('quote_quotes',{project_id:p.id,number,title:p.name});await save('quote_versions',{quote_id:quote.id,name:'A változat'});await db.from('quote_timeline').insert({project_id:p.id,event:'Árajánlat készítése elkezdődött'});await refresh();showView('quotes');await openQuote(quote.id)}
function renderProjects(){
 $('#projects-list').innerHTML=state.projects.map(p=>{const c=state.customers.find(x=>x.id===p.client_id);return `<button class="list-row" data-project-link="${p.id}"><span><strong>${esc(projectTitle(p))}</strong><small>${esc(c?.name||'')} · ${esc(p.status)} · ${esc(p.work_address||'')}</small></span><span>Megnyitás →</span></button>`}).join('')||'<p class="muted">Még nincs projekt.</p>';
 document.querySelectorAll('#projects-list [data-project-link]').forEach(button=>button.onclick=async()=>{try{const p=state.projects.find(x=>x.id===button.dataset.projectLink);showView('customers');await openCustomer(p.client_id);await openProject(p.id)}catch(error){fail(error)}});
}
function renderQuotes(){const out=state.quotes.map(q=>{const p=state.projects.find(x=>x.id===q.project_id);const c=state.customers.find(x=>x.id===p?.client_id);return `<button class="list-row" data-quote="${q.id}"><span><strong>${esc(q.number)} · ${esc(q.title||'')}</strong><small>${esc(c?.name||'')} · ${esc(projectTitle(p))}</small></span><span>Megnyitás →</span></button>`}).join('');$('#quotes-list').innerHTML=out||'<p class="muted">Még nincs árajánlat.</p>';document.querySelectorAll('#quotes-list [data-quote]').forEach(b=>b.onclick=()=>openQuote(b.dataset.quote))}
async function openQuote(id){showView('quotes');state.quote=state.quotes.find(q=>q.id===id);const versions=await rows('quote_versions',q=>q.select('*').eq('quote_id',id).order('created_at'));state.version=versions.find(v=>v.id===state.version?.id)||versions[0];await renderQuote(versions)}
async function renderQuote(versions){const q=state.quote,v=state.version;state.items=await rows('quote_items',x=>x.select('*').eq('version_id',v.id).order('position'));const total=calculateTotal(state.items);const editable=v.status==='draft';const project=state.projects.find(p=>p.id===q.project_id);
 $('#quote-detail').hidden=false;$('#quote-detail').innerHTML=`<section class="panel"><div class="detail-head"><div><p class="eyebrow">${esc(q.number)}</p><h2>${esc(q.title||project?.name||'Árajánlat')}</h2><p class="muted">${esc(projectTitle(project))} · ${esc(v.status)}</p></div><div class="toolbar"><button id="new-version" class="secondary">Változat duplikálása</button><button id="offer-link" class="primary" ${editable?'':'disabled'}>Kiküldés</button></div></div><label>Változat<select id="version-select">${versions.map(x=>`<option value="${x.id}" ${x.id===v.id?'selected':''}>${esc(x.name)} · ${esc(x.status)}</option>`).join('')}</select></label><div class="grid"><label>Érvényesség<input id="valid-until" type="date" value="${esc(q.valid_until||'')}" ${editable?'':'disabled'}></label><label>Részletezés<select id="detail-level" ${editable?'':'disabled'}><option value="detailed" ${q.detail_level==='detailed'?'selected':''}>Részletes</option><option value="total" ${q.detail_level==='total'?'selected':''}>Csak végösszeg</option></select></label></div><label>Feltételek<textarea id="terms" ${editable?'':'disabled'}>${esc(q.terms||'')}</textarea></label><span id="save-state" class="save-state"></span><div class="toolbar">${editable?`<button id="add-item" class="primary">+ Tétel</button><button id="add-plant" class="secondary">+ Növény</button><button id="add-template" class="secondary">Sablon hozzáadása</button>`:''}<button id="print-quote" class="secondary">Nyomtatási nézet</button></div><div id="items-list">${state.items.map(itemHtml).join('')||'<p class="muted">Még nincs tétel.</p>'}</div><div class="summary"><span>Nettó: ${money(total.net)}</span><span>ÁFA: ${money(total.vat)}</span><strong>Bruttó: ${money(total.gross)}</strong></div></section>`;
 $('#version-select').onchange=async e=>{state.version=versions.find(x=>x.id===e.target.value);await renderQuote(versions)};
 $('#new-version').onclick=()=>duplicateVersion();$('#offer-link').onclick=()=>publishVersion();$('#print-quote').onclick=()=>printQuote();
 if(editable){$('#add-item').onclick=()=>editItem();$('#add-plant').onclick=()=>addPlant();$('#add-template').onclick=()=>addTemplate();['valid-until','detail-level','terms'].forEach(key=>{$('#'+key).oninput=()=>{const patch={id:q.id,valid_until:$('#valid-until').value||null,detail_level:$('#detail-level').value,terms:$('#terms').value};debouncedSave(async()=>{await save('quote_quotes',patch);Object.assign(q,patch)})}})}
 document.querySelectorAll('[data-edit-item]').forEach(b=>b.onclick=()=>editItem(state.items.find(x=>x.id===b.dataset.editItem)));
 document.querySelectorAll('[data-delete-item]').forEach(b=>b.onclick=async()=>{if(!confirm('Törli ezt a tételt?'))return;try{await remove('quote_items',b.dataset.deleteItem);await openQuote(q.id)}catch(e){fail(e)}});
 document.querySelectorAll('[data-copy-item]').forEach(b=>b.onclick=async()=>{const old=state.items.find(x=>x.id===b.dataset.copyItem);const {id,created_at,updated_at,...copy}=old;copy.position=state.items.length+1;try{await save('quote_items',copy);await openQuote(q.id)}catch(e){fail(e)}});
 document.querySelectorAll('[data-move-item]').forEach(b=>{b.onclick=async()=>{const i=state.items.findIndex(x=>x.id===b.dataset.moveItem);const j=i+Number(b.dataset.direction);if(j<0||j>=state.items.length)return;try{await Promise.all([save('quote_items',{id:state.items[i].id,position:j+1}),save('quote_items',{id:state.items[j].id,position:i+1})]);await openQuote(q.id)}catch(e){fail(e)}}});
}
function itemHtml(i){const c=calculateItem(i),draft=state.version.status==='draft';return `<article class="quote-item"><div class="item-head"><div><small class="eyebrow">${esc(i.category||'')} / ${esc(i.subcategory||'')}</small><h3>${esc(i.name)}</h3>${i.pricing_required?'<p class="error">Árellenőrzés szükséges: a minta sora nem kapcsolható pontos árlistatételhez.</p>':''}<p>${esc(i.description||'')}</p><p class="muted">${esc(i.quantity1)} ${esc(i.unit1||'')}${i.unit2?` × ${esc(i.quantity2||0)} ${esc(i.unit2)}`:''}</p><p class="muted">Anyag: ${money(c.material)} · Munkadíj: ${money(c.labor)}${c.other?` · Egyéb: ${money(c.other)}`:''}</p><strong>${money(c.net)} nettó</strong></div>${draft?`<div class="item-actions"><button data-edit-item="${i.id}">Szerkeszt</button><button data-copy-item="${i.id}">Másol</button><button data-move-item="${i.id}" data-direction="-1">↑</button><button data-move-item="${i.id}" data-direction="1">↓</button><button data-delete-item="${i.id}">Töröl</button></div>`:''}</div></article>`}
let pendingQuoteSave=null,quoteSavePromise=Promise.resolve();
async function flushQuoteSave(){
 clearTimeout(state.timer);
 if(pendingQuoteSave){const fn=pendingQuoteSave;pendingQuoteSave=null;quoteSavePromise=quoteSavePromise.catch(()=>{}).then(fn).catch(error=>{pendingQuoteSave??=fn;throw error})}
 try{await quoteSavePromise;if($('#save-state'))$('#save-state').textContent='Mentve'}catch(error){if($('#save-state'))$('#save-state').textContent='Mentési hiba';throw error}
}
function debouncedSave(fn){clearTimeout(state.timer);pendingQuoteSave=fn;$('#save-state').textContent='Mentés…';state.timer=setTimeout(()=>flushQuoteSave().catch(fail),650)}
function editItem(item={}){const categories=[...new Set(state.catalog.map(c=>c.category))];const options=state.catalog.map(c=>`<option value="${c.id}" ${item.catalog_id===c.id?'selected':''}>${esc(c.category)} / ${esc(c.subcategory)}</option>`).join('');formDialog(item.id?'Tétel szerkesztése':'Új tétel',`<label>Kategória szerinti szűrés<select id="catalog-category"><option value="">Minden kategória</option>${categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label><label>Árlistatétel<select id="catalog-select" name="catalog_id"><option value="">Egyedi tétel</option>${options}</select></label><div class="grid">${field('category','Főkategória',item.category)}${field('subcategory','Alkategória',item.subcategory)}${field('name','Megnevezés',item.name,'text',true)}${field('quantity1','Mennyiség 1',item.quantity1??1,'number',true)}${field('unit1','Mértékegység 1',item.unit1)}${field('quantity2','Mennyiség 2',item.quantity2,'number')}${field('unit2','Mértékegység 2',item.unit2)}${field('material_unit','Anyag egységár',item.material_unit??0,'number')}${field('labor_unit','Munkadíj egységár',item.labor_unit??0,'number')}${field('other_cost','Egyéb költség',item.other_cost??0,'number')}${field('vat_rate','ÁFA arány (pl. 0,27)',item.vat_rate??0,'number')}</div>${area('description','Leírás',item.description)}${area('internal_note','Belső megjegyzés',item.internal_note)}${area('public_note','Ügyfélnek látható megjegyzés',item.public_note)}${item.pricing_required?'<label><input type="checkbox" name="price_confirmed" value="yes" style="width:auto;min-height:auto"> Az árakat ellenőriztem</label>':''}`,async d=>{const record={...d,version_id:state.version.id,position:item.position??state.items.length+1,...(item.id?{id:item.id}:{})};delete record.price_confirmed;record.catalog_id=d.catalog_id||null;record.pricing_required=Boolean(item.pricing_required&&!d.price_confirmed);for(const k of ['quantity1','quantity2','material_unit','labor_unit','other_cost','vat_rate'])record[k]=d[k]===''?null:Number(d[k]);if(!Number.isFinite(record.quantity1)||record.quantity1<0||record.vat_rate<0||record.vat_rate>1)throw Error('Ellenőrizze a mennyiséget és az ÁFA arányát.');await save('quote_items',record);await openQuote(state.quote.id)});
 $('#catalog-category').onchange=e=>{const select=$('#catalog-select'),selected=select.value;select.innerHTML='<option value="">Egyedi tétel</option>'+state.catalog.filter(c=>!e.target.value||c.category===e.target.value).map(c=>`<option value="${c.id}">${esc(c.category)} / ${esc(c.subcategory)}</option>`).join('');const current=state.catalog.find(c=>c.id===selected);if(current&&![...select.options].some(o=>o.value===selected))select.insertAdjacentHTML('beforeend',`<option value="${current.id}">${esc(current.category)} / ${esc(current.subcategory)}</option>`);select.value=selected};
 $('#catalog-select').onchange=e=>{const c=state.catalog.find(x=>x.id===e.target.value);if(!c)return;const form=$('#dialog-form');for(const [name,value] of Object.entries({category:c.category,subcategory:c.subcategory,name:c.subcategory,description:c.description,unit1:c.unit1,unit2:c.unit2,material_unit:c.material_unit,labor_unit:c.labor_unit,internal_note:c.internal_notes}))if(form.elements[name])form.elements[name].value=value??''};}
async function addPlant(){try{
 const plants=await rows('quote_plants',q=>q.select('id,sku,name,package,category,purchase_net,sale_net,sale_price_placeholder,price_date').eq('active',true).order('name'));
 if(!plants.length){status('A növényárlista üres.',true);return}
 formDialog('Növény hozzáadása',`<label>Növény keresése<input id="plant-search" type="search" placeholder="Név vagy cikkszám"></label><label>Találatok<select name="plant_id" id="plant-select" size="8" required></select></label><p class="muted">A beszerzési ár belső adat. A piros 1 Ft az ismeretlen eladási ár jelzése; az ajánlat előtt adja meg a valódi árat.</p><p id="plant-price-note" class="price-warning" role="status"></p><div class="grid">${field('quantity1','Darabszám',1,'number',true)}${field('material_unit','Eladási egységár (nettó Ft)',1,'number',true)}${field('labor_unit','Munkadíj / db (nettó Ft)',0,'number')}${field('vat_rate','ÁFA arány (pl. 0,27)',0,'number')}</div>`,async d=>{
  const plant=plants.find(p=>p.id===d.plant_id),quantity=Number(d.quantity1),sale=Number(d.material_unit),labor=Number(d.labor_unit||0),vat=Number(d.vat_rate||0);
  if(!plant||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(sale)||sale<=0||!Number.isFinite(labor)||labor<0||!Number.isFinite(vat)||vat<0||vat>1)throw Error('Válasszon növényt, és adjon meg érvényes mennyiséget, eladási árat és ÁFA-arányt.');
  if((plant.sale_price_placeholder||plant.sale_net==null)&&sale===1)throw Error('A piros 1 Ft csak jelzés. Adja meg a valódi eladási árat.');
  await save('quote_items',{version_id:state.version.id,position:state.items.length+1,category:plant.category,subcategory:plant.sku,name:plant.name,quantity1:quantity,unit1:'db',material_unit:sale,labor_unit:labor,other_cost:0,vat_rate:vat,internal_note:`Cikkszám: ${plant.sku}; nettó beszerzési ár: ${plant.purchase_net??'nem ismert'} Ft; árlista dátuma: ${plant.price_date||'nem ismert'}`});await openQuote(state.quote.id)
 });
 const search=$('#plant-search'),select=$('#plant-select'),price=$('#dialog-form').elements.material_unit,note=$('#plant-price-note');
 function updatePrice(){const plant=plants.find(p=>p.id===select.value),placeholder=plant&&(plant.sale_price_placeholder||plant.sale_net==null);price.value=plant?.sale_net??1;price.classList.toggle('price-placeholder',Boolean(placeholder));note.textContent=placeholder?'Eladási ár: 1 Ft — ellenőrizendő.':''}
 function renderPlants(){const term=search.value.trim().toLocaleLowerCase('hu-HU');const found=plants.filter(p=>`${p.sku} ${p.name}`.toLocaleLowerCase('hu-HU').includes(term)).slice(0,40);select.innerHTML=found.map(p=>`<option value="${esc(p.id)}">${esc(p.sku)} · ${esc(p.name)} · beszerzés ${money(p.purchase_net)} · eladás ${money(p.sale_net??1)}</option>`).join('');select.selectedIndex=found.length?0:-1;updatePrice()}
 search.oninput=renderPlants;select.onchange=updatePrice;price.oninput=()=>{const plant=plants.find(p=>p.id===select.value),placeholder=plant&&(plant.sale_price_placeholder||plant.sale_net==null)&&Number(price.value)===1;price.classList.toggle('price-placeholder',Boolean(placeholder));note.textContent=placeholder?'Eladási ár: 1 Ft — ellenőrizendő.':''};renderPlants()
}catch(error){fail(error)}}
async function addTemplate(){formDialog('Sablon hozzáadása',`<label>Sablon<select name="template_id">${state.templates.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></label>`,async d=>{const links=await rows('quote_template_items',q=>q.select('*').eq('template_id',d.template_id).order('position'));for(const link of links){const c=state.catalog.find(x=>x.id===link.catalog_id);await save('quote_items',{version_id:state.version.id,catalog_id:c?.id||null,position:state.items.length+link.position,category:c?.category||link.category,subcategory:c?.subcategory||link.subcategory,name:c?.subcategory||link.subcategory,description:c?.description||null,quantity1:1,unit1:c?.unit1||null,quantity2:c?.unit2?1:null,unit2:c?.unit2||null,material_unit:c?.material_unit||0,labor_unit:c?.labor_unit||0,internal_note:c?.internal_notes||null,pricing_required:!c})}await openQuote(state.quote.id)})}
async function duplicateVersion(){try{const v=state.version;const copy=await save('quote_versions',{quote_id:v.quote_id,name:prompt('Új változat neve',v.name+' másolat')||v.name+' másolat'});for(const i of state.items){const {id,created_at,updated_at,...rest}=i;await save('quote_items',{...rest,version_id:copy.id})}state.version=copy;await openQuote(state.quote.id)}catch(e){fail(e)}}
async function publishVersion(){try{if(!state.items.length)throw Error('Az ajánlat üres.');if(state.items.some(i=>i.pricing_required))throw Error('Egyes sablontételek árát még ellenőrizni kell.');const q=state.quote,v=state.version,p=state.projects.find(x=>x.id===q.project_id),c=state.customers.find(x=>x.id===p.client_id),total=calculateTotal(state.items);const snapshot={purpose:'offer',project_code:p.project_code,number:q.number,date:new Date().toISOString(),valid_until:q.valid_until,customer:c.name,work_address:p.work_address,title:q.title,version:v.name,detail_level:q.detail_level,terms:q.terms,items:state.items.map(i=>({name:i.name,description:i.description,quantity1:i.quantity1,unit1:i.unit1,quantity2:i.quantity2,unit2:i.unit2,public_note:i.public_note,net:calculateItem(i).net,vat:calculateItem(i).vat,gross:calculateItem(i).gross})),total:{net:total.net,vat:total.vat,gross:total.gross}};await save('quote_versions',{id:v.id,status:'published',published_at:new Date().toISOString(),published_snapshot:snapshot});await db.from('quote_timeline').insert({project_id:p.id,event:'Árajánlat elkészült és kiküldhető'});await createToken(p.id,v.id,'offer',c.email,q.number);await openQuote(q.id)}catch(e){fail(e)}}
async function createToken(projectId,versionId,purpose,email='',number=''){try{
 let token;
 if(purpose==='request'){token=await rpc('quote_request_link_create',{p_project:projectId})}
 else{const bytes=crypto.getRandomValues(new Uint8Array(32));token=Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(token))),x=>x.toString(16).padStart(2,'0')).join('');await save('quote_public_tokens',{project_id:projectId,version_id:versionId,purpose,token_hash:hash,expires_at:new Date(Date.now()+30*86400000).toISOString()});}
 const link=new URL('client.html',location.href);link.searchParams.set('token',token);const url=link.href;
 formDialog(purpose==='request'?'Ügyfél adatbekérő küldése':'Biztonságos ügyféllink',`<p>A link 30 napig érvényes. Csak azzal oszd meg, akinek szól.</p><label>Link<input id="generated-link" value="${esc(url)}" readonly></label><div class="toolbar"><button type="button" id="copy-link" class="secondary">Link másolása</button><button type="button" id="email-link" class="secondary">Email küldése</button>${navigator.share?'<button type="button" id="share-link" class="secondary">Link megosztása</button>':''}</div>`,async()=>{});
 $('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText(url);status('Link másolva.')}catch{const input=$('#generated-link');input.focus();input.select();status('Másold ki a kijelölt linket.')}};
 $('#email-link').onclick=()=>purpose==='offer'?offerEmail(email,number,url):composeEmail({to:email,subject:'Díszkertek – projektadatok',body:['Kedves Ügyfelünk!','','Kérjük, töltse ki az adatbekérőt:',url,'','Üdvözlettel:','Díszkertek'].join('\n')});
 const share=$('#share-link');if(share)share.onclick=async()=>{try{await navigator.share({title:'Díszkertek – '+(purpose==='request'?'adatbekérő':'árajánlat'),url})}catch(error){if(error.name!=='AbortError')status('A megosztás nem sikerült. Másold ki a linket.',true)}};
 if(purpose==='offer'){const {error}=await db.from('quote_timeline').insert({project_id:projectId,event:'Ajánlati link létrehozva'});if(error)throw error}
 status('A link elkészült, másolható vagy elküldhető.');
}catch(error){fail(error)}}

async function printQuote(){const d=state.version.published_snapshot;if(!d){status('Nyomtatáshoz előbb küldje ki az ajánlatot.',true);return}const root=document.createElement('section');root.id='admin-print';root.innerHTML=`<header class="print-brand"><img class="document-logo" src="assets/diszkertek-logo.png" alt="Díszkertek"></header><p>${esc(d.number)} · ${esc(d.version)}</p><h1>Árajánlat</h1>${d.project_code?`<p>Projekt: ${esc(d.project_code)}</p>`:''}<p>${esc(d.customer)}<br>${esc(d.work_address||'')}</p><p>Kelt: ${dateTime(d.date)} · Érvényesség: ${esc(d.valid_until||'egyeztetés szerint')}</p>${d.detail_level==='detailed'?(d.items||[]).map(i=>`<div class="offer-row"><span>${esc(i.name)} · ${esc(i.quantity1)} ${esc(i.unit1||'')}${i.unit2?` × ${esc(i.quantity2)} ${esc(i.unit2)}`:''}</span><strong>${money(i.gross)}</strong></div>`).join(''):''}<div class="summary"><span>Nettó: ${money(d.total.net)}</span><span>ÁFA: ${money(d.total.vat)}</span><strong>Bruttó: ${money(d.total.gross)}</strong></div><p>${esc(d.terms||'')}</p>`;document.body.append(root);try{await root.querySelector('img').decode()}catch{root.remove();status('A logó nem töltődött be. Ellenőrizd az internetkapcsolatot, majd próbáld újra.',true);return}document.body.classList.add('has-admin-print');window.print();setTimeout(()=>{root.remove();document.body.classList.remove('has-admin-print')},1000)}
document.addEventListener('quote:before-update',event=>event.detail.waitUntil((async()=>{if($('#form-dialog').open)throw Error('Előbb mentsd vagy zárd be a megnyitott űrlapot.');await flushQuoteSave()})()));
init().catch(fail);
