import { configured, rpc } from './services/supabase-service.js';
import { money, dateTime } from './modules/quote-calculator.js';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&gt;','>':'&lt;','"':'&quot;',"'":'&#39;'}[c]));
const token=new URLSearchParams(location.search).get('token');
function status(message,error=false){$('#client-status').textContent=message;$('#client-status').classList.toggle('error',error)}
function err(error){console.error(error);status('A művelet nem sikerült. Ellenőrizze a kapcsolatot, majd próbálja újra.',true)}
async function init(){if(!configured||!token){status('A link nem elérhető.',true);return}try{const data=await rpc('quote_public_read',{p_token:token});if(!data){status('A link lejárt vagy már nem érvényes.',true);return}if(data.purpose==='request')renderRequest(data);else if(data.purpose==='offer')renderOffer(data);else status('A link nem elérhető.',true)}catch(error){err(error)}}
function renderRequest(data){$('#client-content').innerHTML=`<div class="offer-title"><p class="eyebrow">PROJEKTADATOK</p><h1>${esc(data.project)}</h1><p>${esc(data.work_address||'')}</p></div><p>Kérjük, adja meg a munkához szükséges adatokat. Az egyes részeket külön nyithatja meg.</p><form id="request-form"><details open><summary>Kapcsolattartás</summary><div class="grid"><label>Név<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Telefon<input name="phone" type="tel" required></label><label>Helyszín<input name="work_address"></label></div></details><details><summary>A tervezett munka</summary><label>Milyen munkát szeretne?<select name="work_type"><option value="">Válasszon</option><option>Kertépítés</option><option>Füvesítés</option><option>Öntözőrendszer</option><option>Növénytelepítés</option><option>Térkövezés</option><option>Egyéb</option></select></label><label>Leírás<textarea name="description"></textarea></label><div class="grid"><label>Terület (m²)<input name="area_m2" type="number" min="0" step="any"></label><label>Hosszúság (fm)<input name="length_fm" type="number" min="0" step="any"></label><label>Szélesség (m)<input name="width_m" type="number" min="0" step="any"></label><label>Darabszám<input name="count" type="number" min="0" step="1"></label></div></details><details><summary>Helyszín és közművek</summary><div class="grid"><label>Kapuszélesség (cm)<input name="gate_cm" type="number" min="0"></label><label>Géppel megközelíthető?<select name="machine_access"><option value="">Nem ismert</option><option value="yes">Igen</option><option value="no">Nem</option></select></label><label>Van víz?<select name="water"><option value="">Nem ismert</option><option value="yes">Igen</option><option value="no">Nem</option></select></label><label>Van áram?<select name="power"><option value="">Nem ismert</option><option value="yes">Igen</option><option value="no">Nem</option></select></label></div><label>Egyéb megközelítési információ<textarea name="access_note"></textarea></label></details><details><summary>Dokumentumok és megjegyzés</summary><p class="muted">A kiválasztott fájlok nem kerülnek a szerverre. A fájlokat az emailprogramjában külön kell csatolnia. Itt csak a fájlok neve és típusa kerül rögzítésre.</p><label>Fájlok kiválasztása<input id="attachments" type="file" multiple accept="image/*,.pdf,.doc,.docx"></label><label>Megjegyzés<textarea name="note"></textarea></label></details><button class="primary">Adatok elküldése</button></form>`;
 $('#request-form').onsubmit=async event=>{event.preventDefault();const form=event.target;const answers=Object.fromEntries(new FormData(form));answers.files=Array.from($('#attachments').files).map(f=>({name:f.name,type:f.type,size:f.size}));try{const ok=await rpc('quote_public_submit',{p_token:token,p_answers:answers});if(!ok)throw Error('Sikertelen mentés');form.remove();status('Köszönjük, az adatokat rögzítettük. A kiválasztott fájlokat kérjük, külön csatolja az emailhez.') }catch(error){err(error)}}}
function renderOffer(data){const items=data.detail_level==='detailed'?data.items||[]:[];$('#client-content').innerHTML=`<div class="offer-title"><p class="eyebrow">${esc(data.number)} · ${esc(data.version)}</p><h1>Árajánlat</h1><p><strong>${esc(data.customer)}</strong><br>${esc(data.work_address||'')}</p><p class="muted">Kelt: ${dateTime(data.date)} · Érvényes: ${esc(data.valid_until||'egyeztetés szerint')}</p></div><h2>${esc(data.title||'Ajánlatunk')}</h2>${items.map(i=>`<div class="offer-row"><div><strong>${esc(i.name)}</strong><small>${esc(i.description||'')}</small><small>${esc(i.quantity1)} ${esc(i.unit1||'')}${i.unit2?` × ${esc(i.quantity2)} ${esc(i.unit2)}`:''}</small><small>${esc(i.public_note||'')}</small></div><strong>${money(i.gross)}</strong></div>`).join('')}<div class="summary"><span>Nettó: ${money(data.total?.net)}</span><span>ÁFA: ${money(data.total?.vat)}</span><strong>Bruttó: ${money(data.total?.gross)}</strong></div>${data.terms?`<section><h3>Feltételek</h3><p>${esc(data.terms)}</p></section>`:''}<div class="client-actions"><div class="toolbar"><button id="print" class="secondary">Nyomtatás / Mentés PDF-ként</button></div><h3>Visszajelzés</h3><form id="decision-form"><label>Név<input name="name" required minlength="2"></label><label>Megjegyzés<textarea name="note"></textarea></label><label><input type="checkbox" name="confirm" style="width:auto;min-height:auto"> Az ajánlat tartalmát megismertem.</label><div class="toolbar"><button name="decision" value="accepted" class="primary">Árajánlat elfogadása</button><button name="decision" value="change" class="secondary">Módosítást kérek</button><button name="decision" value="rejected" class="danger">Nem kérem</button></div></form></div>`;
 $('#print').onclick=()=>window.print();$('#decision-form').onsubmit=async event=>{event.preventDefault();const submitter=event.submitter;const form=event.target;const d=new FormData(form);const decision=submitter.value;if(decision==='accepted'&&!form.elements.confirm.checked){status('Az elfogadáshoz jelölje be a nyilatkozatot.',true);return}try{const ok=await rpc('quote_public_decide',{p_token:token,p_decision:decision,p_name:d.get('name'),p_note:d.get('note'),p_confirm:form.elements.confirm.checked});if(!ok)throw Error('Sikertelen visszajelzés');form.remove();status(decision==='accepted'?'Az ajánlat elfogadását rögzítettük.':decision==='change'?'A módosítási kérését rögzítettük.':'A döntését rögzítettük.')}catch(error){err(error)}}}
init();
