import { rows, rpc } from '../services/supabase-service.js';
import { money } from './quote-calculator.js';
import { irrigationTotals, robotRounding } from './source-calculator.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(head,body)=>`<div class="source-table-wrap" tabindex="0" aria-label="Részletes adatok"><table class="source-table"><thead><tr>${head.map(v=>`<th scope="col">${esc(v)}</th>`).join('')}</tr></thead><tbody>${body.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
export async function mountPriceSources(container,{catalog,quote,formDialog,onApplied,fail}){
 container.innerHTML='<details class="source-section"><summary>Belső árlista és költségrészletező</summary><div data-source-content></div></details>';
 const section=container.querySelector('details'),content=container.querySelector('[data-source-content]');let loaded=false,loading=false;
 section.addEventListener('toggle',async()=>{
 if(!section.open||loaded||loading)return;loading=true;content.textContent='Árforrások betöltése…';
 try{
 const [components,breakdown,packages]=await Promise.all([rows('quote_price_components',q=>q.select('*').order('position')),rows('quote_price_breakdown',q=>q.select('*').order('source_group').order('source_row')),rows('quote_source_packages',q=>q.select('*').order('source_key'))]);
 if(!container.isConnected)return;
 content.innerHTML=`<h3>Excel árlista</h3><label>Keresés az árlistában<input type="search" data-catalog-search autocomplete="off"></label><label>Árlistatétel<select data-catalog-detail></select></label><div data-catalog-info></div><details><summary>Excel Részletező · ${breakdown.length} sor</summary><label>Keresés a részletezőben<input data-breakdown-search type="search"></label><div data-breakdown-info></div><div class="toolbar"><button type="button" data-page-prev>Előző</button><span data-page-label></span><button type="button" data-page-next>Következő</button></div></details><h3>Kiegészítő árforrások</h3><p class="muted">Az eredeti mellékletek adatai. Az ajánlatba másolás új, ellenőrizendő változatot hoz létre.</p><label>Árforrás<select data-package>${packages.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><div data-package-info></div>`;
 const select=content.querySelector('[data-catalog-detail]'),info=content.querySelector('[data-catalog-info]');
 const showCatalog=()=>{const c=catalog.find(c=>c.id===select.value);if(!c){info.textContent='Nincs találat.';return}const parts=components.filter(p=>p.catalog_id===c.id);info.innerHTML=`<p><strong>${esc(c.category)} / ${esc(c.subcategory)}</strong></p><p>${esc(c.description)}</p><dl class="source-values"><div><dt>Mértékegységek</dt><dd>${esc(c.unit1)}${c.unit2?` × ${esc(c.unit2)}`:''}</dd></div><div><dt>Anyag egységára</dt><dd>${money(c.material_unit)}</dd></div><div><dt>Munkadíj egységára</dt><dd>${money(c.labor_unit)}</dd></div></dl><p>${esc(c.internal_notes)}</p><small>Forrás: ${esc(c.source)} · Excel-sor: ${esc(c.source_row)}</small>${parts.length?`<h4>Tételösszetevők</h4>${table(['Megnevezés','Mennyiség','Egység'],parts.map(p=>[esc(p.name),esc(p.quantity),esc(p.unit)]))}`:'<p class="muted">Ehhez a tételhez nincs külön összetevő az Excelben.</p>'}`;};
 const filterCatalog=()=>{const query=content.querySelector('[data-catalog-search]').value.trim().toLocaleLowerCase('hu');const selected=select.value;select.innerHTML=catalog.filter(c=>`${c.category} ${c.subcategory} ${c.description||''}`.toLocaleLowerCase('hu').includes(query)).map(c=>`<option value="${c.id}">${esc(c.category)} / ${esc(c.subcategory)}</option>`).join('');if(Array.from(select.options).some(o=>o.value===selected))select.value=selected;showCatalog();};
 select.onchange=showCatalog;content.querySelector('[data-catalog-search]').oninput=filterCatalog;filterCatalog();
 let page=0;const renderBreakdown=()=>{const query=content.querySelector('[data-breakdown-search]').value.trim().toLocaleLowerCase('hu');const list=breakdown.filter(r=>`${r.heading||''} ${r.line_name||''} ${r.note||''}`.toLocaleLowerCase('hu').includes(query));const pages=Math.max(1,Math.ceil(list.length/20));page=Math.min(page,pages-1);content.querySelector('[data-breakdown-info]').innerHTML=table(['Csoport / sor','Megnevezés','Anyag','Munkadíj','Megjegyzés'],list.slice(page*20,(page+1)*20).map(r=>[`${r.source_group} / ${r.source_row}`,`${esc(r.heading)}<br>${esc(r.line_name)}`,esc(r.material_value),esc(r.labor_value),esc(r.note)]));content.querySelector('[data-page-label]').textContent=`${page+1} / ${pages} oldal · ${list.length} sor`;content.querySelector('[data-page-prev]').disabled=page===0;content.querySelector('[data-page-next]').disabled=page===pages-1;};
 content.querySelector('[data-breakdown-search]').oninput=()=>{page=0;renderBreakdown()};content.querySelector('[data-page-prev]').onclick=()=>{page--;renderBreakdown()};content.querySelector('[data-page-next]').onclick=()=>{page++;renderBreakdown()};renderBreakdown();
 const showPackage=()=>{
 const p=packages.find(p=>p.id===content.querySelector('[data-package]').value),box=content.querySelector('[data-package-info]');if(!p){box.textContent='Nincs kiegészítő árforrás.';return}const data=p.payload;
 const common=`<p><strong>${esc(p.name)}</strong><br><small>${esc(p.source_file)}</small></p><button type="button" class="secondary" data-apply-source>Új ajánlatváltozat ebből</button>`;
 if(data.type==='irrigation'){
 box.innerHTML=common+'<p>A belső költségek a teljes megadott mennyiségre vonatkoznak. Az eladási ár külön ellenőrizendő; a másolatban 1 Ft piros jelzéssel szerepel.</p>'+table(['Tétel','Mennyiség','Anyag','Kiegészítő anyag','Szállítás','Munkadíj','Összesen'],data.lines.map(r=>[esc(r.name),`${esc(r.quantity)} ${esc(r.unit)}`,money(r.material),`${esc(r.extra_name)}<br>${money(r.extra_material)}`,money(r.shipping),money(r.labor),money(r.total)]))+`<h4>Meglévő elemek miatti költségcsökkenés</h4><p>Jelölje a megtartható elemeket. A sáv a melléklet minimum–maximum becslését mutatja.</p>${data.discounts.map((r,i)=>`<label class="check-label"><input type="checkbox" data-deduction="${i}" checked> ${esc(r.name)} · ${esc(r.quantity)} ${esc(r.unit)} · ${money(r.material_min+r.labor_min)}–${money(r.material_max+r.labor_max)}<small>${esc(r.note)}</small></label>`).join('')}<p data-irrigation-total class="notice"></p><p>${esc(data.note)}</p><details><summary>Eredeti cellák és képletek</summary>${table(['Cella','Tartalom / képlet','Excel-eredmény'],data.cells.map(c=>[esc(c.cell),esc(c.value),esc(c.cached)]))}</details>`;
 const totals=()=>{const selected=Array.from(box.querySelectorAll('[data-deduction]:checked'),i=>Number(i.dataset.deduction));const t=irrigationTotals(data,selected);box.querySelector('[data-irrigation-total]').textContent=`Alapköltség: ${money(t.base)} · Várható költség: ${money(t.low)}–${money(t.high)}`;};box.querySelectorAll('[data-deduction]').forEach(i=>i.onchange=totals);totals();
 }else{
 box.innerHTML=common+table(['Anyag','Bruttó egységár','Darab','Bruttó összeg'],data.materials.map(r=>[esc(r.name),money(r.unit_price),esc(r.quantity),money(r.total)]))+table(['Összesítés','Nettó','Bruttó'],['Anyag költség','Telepítés','Tereprendezés','Összesen'].map(name=>[esc(name),money(data.summaries[name].net),money(data.summaries[name].gross)]))+`<p class="notice">A PDF eredeti bruttó végösszege: ${money(data.total_gross)}. A kerekített nettó árakból 27% ÁFÁ-val számított eltérés: ${robotRounding(data).toLocaleString('hu-HU',{minimumFractionDigits:2,maximumFractionDigits:2})} Ft. A másolt változat árait kiküldés előtt ellenőrizze.</p>`;
 }
 box.querySelector('[data-apply-source]').onclick=()=>formDialog('Új ajánlatváltozat',`<p>${esc(p.name)} · ${esc(p.source_file)}</p><p>Az új változat piszkozat lesz. Kiküldés előtt minden tételnél ellenőrizze az eladási árat.</p><label>Változat neve<input name="name" required maxlength="200" value="${esc(p.name)}"></label>`,async d=>{const id=await rpc('quote_source_package_apply',{p_quote:quote.id,p_source:p.id,p_name:d.name});await onApplied(id);return 'Az új, ellenőrizendő ajánlatváltozat elkészült.';});
 };
 content.querySelector('[data-package]').onchange=showPackage;showPackage();loaded=true;
 }catch(e){content.innerHTML='<p class="error">Az árforrások nem töltődtek be. Zárja be, majd nyissa ki újra ezt a részt.</p>';fail(e)}finally{loading=false}
 });
}
